"""
Django settings for сonfig project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LANGUAGE_CODE = "ru"  # Язык по умолчанию

LANGUAGES = [
    ("ru", _("Russian")),
    ("uk", _("Ukrainian")),
    ("en", _("English")),
]

USE_I18N = True  # Включает поддержку перевода
USE_TZ = True  # Включает поддержку часовых поясов (для нас это Europe/Kyiv)

# Путь, где Django будет искать файлы переводов (.po)
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-5)@!a2=xq-8^$zx&kx!f8k55lg-v9ph4mzr=y#oh2yu9&flvl6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",  # Базовая тема. ОБЯЗАТЕЛЬНО перед django.contrib.admin
    "unfold.contrib.filters",  # Очень полезно: делает фильтры (по датам, статусам) красивыми и компактными
    "unfold.contrib.forms",  # Полезно: улучшает стандартные поля ввода
    "unfold.contrib.inlines",  # ОБЯЗАТЕЛЬНО: так как мы используем Inlines для реквизитов и контактов
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "catalogs.apps.CatalogsConfig",
    "documents.apps.DocumentsConfig",
    "registers.apps.RegistersConfig",
    "django_countries",
]

MIDDLEWARE = [
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "сonfig.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "сonfig.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Kyiv"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Список кодов валют, которые будут доступны в проекте
CURRENCIES = ("UAH", "USD")

# Отображение имен валют в выпадающих списках
CURRENCY_CHOICES = [
    ("UAH", "UAH"),
    ("USD", "USD"),
]

# Валюта по умолчанию
DEFAULT_CURRENCY = "UAH"

UNFOLD = {
    "SHOW_LANGUAGES": True,
}
