# Generated by Django 6.0.4 on 2026-04-30 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('site_name', models.CharField(blank=True, max_length=255, verbose_name='Название на сайте')),
                ('fiscal_name', models.CharField(blank=True, max_length=255, verbose_name='Название для чеков')),
                ('sku', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Артикул (SKU)')),
                ('external_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID в OpenCart')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='BrandSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.brand')),
            ],
            options={
                'verbose_name': 'Поставщик бренда',
                'verbose_name_plural': 'Поставщики брендов',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='main_supplier',
            field=models.ForeignKey(blank=True, help_text='Выберите из списка уже добавленных поставщиков бренда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_for_brand', to='catalogs.brandsupplier', verbose_name='Основной поставщик'),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('legal_type', models.CharField(choices=[('IND', 'Физическое лицо'), ('FOP', 'ФОП'), ('OTH', 'Организация (ООО, ПАО и т.д.)'), ('HLD', 'Холдинг / Группа компаний')], default='IND', max_length=3, verbose_name='Тип контрагента')),
                ('last_name', models.CharField(db_index=True, max_length=150, verbose_name='Фамилия / Название')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('ownership_type', models.CharField(blank=True, help_text='Например: ООО, ПП, ПАО. Для ФОП заполнится автоматически.', max_length=20, verbose_name='Аббревиатура типа')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_supplier', models.BooleanField(default=True, verbose_name='Поставщик')),
                ('is_customer', models.BooleanField(default=True, verbose_name='Покупатель')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('parent_holding', models.ForeignKey(blank=True, limit_choices_to={'legal_type': 'HLD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='catalogs.contractor', verbose_name='Входит в холдинг')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.AddField(
            model_name='brandsupplier',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.contractor'),
        ),
        migrations.AddField(
            model_name='brand',
            name='suppliers',
            field=models.ManyToManyField(related_name='brands', through='catalogs.BrandSupplier', to='catalogs.contractor', verbose_name='Поставщики бренда'),
        ),
        migrations.CreateModel(
            name='ContractorLegalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='ИНН / ЕГРПОУ')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_details', to='catalogs.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Официальные реквизиты',
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('supplier_sku', models.CharField(blank=True, help_text='Как этот товар называется/кодируется в базе поставщика', max_length=64, verbose_name='Артикул поставщика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Товар')),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.contractor', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик товара',
                'verbose_name_plural': 'Поставщики товара',
                'unique_together': {('product', 'supplier')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='main_supplier',
            field=models.ForeignKey(blank=True, help_text='Выберите из списка уже добавленных поставщиков', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_for_product', to='catalogs.productsupplier', verbose_name='Основной поставщик'),
        ),
        migrations.AlterUniqueTogether(
            name='brandsupplier',
            unique_together={('brand', 'supplier')},
        ),
    ]
