# Generated by Django 6.0.4 on 2026-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_brandsupplier_comment_productsupplier_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsupplier',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
