# Generated by Django 6.0.4 on 2026-04-30 12:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_brandsupplier_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='usd_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Личный курс поставщика для конвертации цен в прайсах', max_digits=10, max_length=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Курс доллара (USD/UAH)'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='use_usd_prices',
            field=models.BooleanField(default=False, help_text='Если включено, цены в прайсах этого поставщика будут автоматически конвертироваться в UAH по указанному курсу', verbose_name='Цены в USD'),
        ),
    ]
