# Generated by Django 6.0.4 on 2026-04-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_contractor_usd_rate_contractor_use_usd_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Сайт, Instagram, Прайс', max_length=100, verbose_name='Название')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalogs.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
