# Generated by Django 6.0.4 on 2026-05-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_contractorlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название типа')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Тип населенного пункта',
                'verbose_name_plural': 'Типы населенных пунктов',
            },
        ),
    ]
