# Generated by Django 6.0.4 on 2026-05-01 06:20

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_settlementtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('country', django_countries.fields.CountryField(default='UA', max_length=2, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Область/Район')),
                ('ref_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID Новой Почты')),
                ('settlement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='catalogs.settlementtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
                'ordering': ['name'],
            },
        ),
    ]
