# Generated by Django 6.0.4 on 2026-05-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('is_virtual', models.BooleanField(default=False, help_text='Используется для дропшиппинга или учета остатков поставщика', verbose_name='Виртуальный склад')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='catalogs.settlement', verbose_name='Населенный пункт')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
    ]
