# Generated by Django 6.0.4 on 2026-05-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorlegaldetails',
            name='iban',
        ),
    ]
