# Generated by Django 6.0.4 on 2026-05-04 05:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_remove_contractorlegaldetails_iban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='dt_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='dt_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='brandsupplier',
            old_name='dt_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='brandsupplier',
            old_name='dt_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='dt_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='dt_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dt_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dt_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='productsupplier',
            old_name='dt_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='productsupplier',
            old_name='dt_updated',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='usd_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Личный курс поставщика для конвертации цен в прайсах', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Курс доллара (USD/UAH)'),
        ),
    ]
