# Generated by Django 6.0.4 on 2026-05-04 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_rename_dt_created_brand_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
