# Generated by Django 6.0.4 on 2026-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_warehouse_created_warehouse_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorlegaldetails',
            name='legal_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Юридический адрес'),
        ),
    ]
