# Generated by Django 6.0.4 on 2026-05-04 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_alter_contractorlegaldetails_legal_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('mfo', models.CharField(blank=True, max_length=6, verbose_name='МФО')),
                ('currency', models.CharField(default='UAH', help_text='Код валюты (UAH, USD, EUR)', max_length=3, verbose_name='Валюта счета')),
                ('iban', models.CharField(db_index=True, max_length=34, unique=True, verbose_name='IBAN')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='catalogs.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
                'ordering': ['bank_name'],
            },
        ),
    ]
