# Generated by Django 6.0.4 on 2026-05-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0013_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='primary_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogs.bankaccount', verbose_name='Основной счет'),
        ),
    ]
