# Generated by Django 6.0.5 on 2026-05-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_contractor_primary_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='is_manufacturer',
            field=models.BooleanField(default=True, verbose_name='Производитель'),
        ),
    ]
