# Generated by Django 6.0.5 on 2026-05-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0015_contractor_is_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='manufacturer',
            field=models.ForeignKey(default=1, limit_choices_to={'is_manufacturer': True}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.contractor', verbose_name='Контрагент производителя'),
            preserve_default=False,
        ),
    ]
