# Generated by Django 6.0.5 on 2026-05-12 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0018_product_brand_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='manufacturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_manufacturer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.contractor', verbose_name='Контрагент производителя'),
        ),
    ]
