# Generated by Django 6.0.5 on 2026-05-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0019_alter_brand_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Сначала выберите основную категорию, чтобы увидеть список доступных подкатегорий', related_name='subcategory_products', to='catalogs.category', verbose_name='Подкатегории'),
        ),
    ]
