# Generated by Django 6.0.5 on 2026-05-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0020_product_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('full_name', models.TextField(blank=True, verbose_name='Полное название')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('is_default', models.BooleanField(default=False, help_text='Эта организация будет автоматически выбираться в новых документах', verbose_name='Использовать по умолчанию')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
