# Generated by Django 6.0.5 on 2026-05-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0021_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменена'),
        ),
    ]
