# Generated by Django 6.0.5 on 2026-05-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0022_alter_organization_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
