# Generated by Django 6.0.5 on 2026-05-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0023_alter_organization_created_and_more'),
        ('documents', '0028_alter_purchaseorder_organization_paymentorderout_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='ContractorBankAccount',
        ),
    ]
