# Generated by Django 6.0.5 on 2026-05-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0024_rename_bankaccount_contractorbankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorbankaccount',
            options={'verbose_name': 'Счет контрагента', 'verbose_name_plural': 'Счета контрагентов'},
        ),
        migrations.AlterField(
            model_name='contractorbankaccount',
            name='currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта счета'),
        ),
        migrations.CreateModel(
            name='OurBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('mfo', models.CharField(blank=True, max_length=6, verbose_name='МФО')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта счета')),
                ('iban', models.CharField(db_index=True, max_length=34, unique=True, verbose_name='IBAN')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основной счет')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_accounts', to='catalogs.organization', verbose_name='Наша организация')),
            ],
            options={
                'verbose_name': 'Наш расчетный счет',
                'verbose_name_plural': 'Наши расчетные счета',
            },
        ),
    ]
