# Generated by Django 6.0.5 on 2026-05-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0025_alter_contractorbankaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorbankaccount',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Основной счет'),
        ),
    ]
