# Generated by Django 6.1 on 2026-08-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0026_contractorbankaccount_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='default_price_type',
            field=models.CharField(choices=[('small_wholesale', 'Мелкий опт'), ('wholesale', 'Опт'), ('large_wholesale', 'Крупный опт')], default='wholesale', max_length=20, verbose_name='Тип цены по умолчанию'),
        ),
    ]
