# Generated by Django 6.1 on 2026-08-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0027_contractor_default_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Розничный магазин',
                'verbose_name_plural': 'Розничные магазины',
                'ordering': ('name',),
            },
        ),
    ]
