# Generated by Django 6.1 on 2026-08-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0028_retailstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailstore',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Этот магазин будет автоматически выбираться в новых установках розничных цен', verbose_name='Использовать по умолчанию'),
        ),
    ]
