# Generated by Django 6.1 on 2026-09-01

import catalogs.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0029_retailstore_is_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "symbol",
                    models.CharField(max_length=20, verbose_name="Обозначение"),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text=(
                            "Определяет точность количества и шаг стрелок в форме заказа"
                        ),
                        validators=[django.core.validators.MaxValueValidator(6)],
                        verbose_name="Знаков после запятой",
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                default=catalogs.models.get_default_measurement_unit_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalogs.measurementunit",
                verbose_name="Единица измерения",
            ),
        ),
    ]
