# Generated by Django 6.1 on 2026-09-13 17:05

from django.db import migrations, models


def seed_delivery_methods(apps, schema_editor):
    Method = apps.get_model("catalogs", "DeliveryMethod")
    for name, kind in [
        ("Новая почта", "carrier"), ("Укрпочта", "carrier"),
        ("Деливери", "carrier"), ("Meest Express", "carrier"), ("Самовывоз", "pickup"),
    ]:
        Method.objects.using(schema_editor.connection.alias).get_or_create(name=name, defaults={"kind": kind})


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0030_measurementunit_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('kind', models.CharField(choices=[('carrier', 'Перевозчик'), ('pickup', 'Самовывоз')], default='carrier', max_length=20, verbose_name='Тип доставки')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(seed_delivery_methods, migrations.RunPython.noop),
    ]
