# Generated by Django 6.1 on 2026-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0031_deliverymethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaArea',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False, verbose_name='Ref Новой почты')),
                ('description', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Новая почта: область',
                'verbose_name_plural': 'Новая почта: области',
                'ordering': ('description',),
            },
        ),
    ]
