# Generated by Django 6.1 on 2026-09-13 19:08

import django.db.models.deletion
from django.db import migrations, models


# Verified mapping from getAreas to getSettlementAreas (2026-09-13).
AREA_REFS = {
    "71508128-9b87-11de-822f-000c2965ae0e": "dcaad3d6-4b33-11e4-ab6d-005056801329",
    "71508129-9b87-11de-822f-000c2965ae0e": "dcaad5a7-4b33-11e4-ab6d-005056801329",
    "7150812a-9b87-11de-822f-000c2965ae0e": "dcaad676-4b33-11e4-ab6d-005056801329",
    "7150812b-9b87-11de-822f-000c2965ae0e": "dcaad735-4b33-11e4-ab6d-005056801329",
    "7150812c-9b87-11de-822f-000c2965ae0e": "dcaad81c-4b33-11e4-ab6d-005056801329",
    "7150812d-9b87-11de-822f-000c2965ae0e": "dcaad8fb-4b33-11e4-ab6d-005056801329",
    "7150812e-9b87-11de-822f-000c2965ae0e": "dcaad993-4b33-11e4-ab6d-005056801329",
    "7150812f-9b87-11de-822f-000c2965ae0e": "dcaada26-4b33-11e4-ab6d-005056801329",
    "71508130-9b87-11de-822f-000c2965ae0e": "dcaadac6-4b33-11e4-ab6d-005056801329",
    "71508131-9b87-11de-822f-000c2965ae0e": "dcaadb64-4b33-11e4-ab6d-005056801329",
    "71508132-9b87-11de-822f-000c2965ae0e": "dcaadbf9-4b33-11e4-ab6d-005056801329",
    "71508133-9b87-11de-822f-000c2965ae0e": "dcaadc91-4b33-11e4-ab6d-005056801329",
    "71508134-9b87-11de-822f-000c2965ae0e": "dcaadd3a-4b33-11e4-ab6d-005056801329",
    "71508135-9b87-11de-822f-000c2965ae0e": "dcaaddd7-4b33-11e4-ab6d-005056801329",
    "71508136-9b87-11de-822f-000c2965ae0e": "dcaade6d-4b33-11e4-ab6d-005056801329",
    "71508137-9b87-11de-822f-000c2965ae0e": "dcaadf02-4b33-11e4-ab6d-005056801329",
    "71508138-9b87-11de-822f-000c2965ae0e": "dcaadfa0-4b33-11e4-ab6d-005056801329",
    "71508139-9b87-11de-822f-000c2965ae0e": "dcaae036-4b33-11e4-ab6d-005056801329",
    "7150813a-9b87-11de-822f-000c2965ae0e": "dcaae303-4b33-11e4-ab6d-005056801329",
    "7150813b-9b87-11de-822f-000c2965ae0e": "dcaae3a1-4b33-11e4-ab6d-005056801329",
    "7150813c-9b87-11de-822f-000c2965ae0e": "dcaae44b-4b33-11e4-ab6d-005056801329",
    "7150813d-9b87-11de-822f-000c2965ae0e": "dcaae4e5-4b33-11e4-ab6d-005056801329",
    "7150813e-9b87-11de-822f-000c2965ae0e": "dcaae57c-4b33-11e4-ab6d-005056801329",
    "7150813f-9b87-11de-822f-000c2965ae0e": "dcaae60e-4b33-11e4-ab6d-005056801329",
    "71508140-9b87-11de-822f-000c2965ae0e": "dcaae6a8-4b33-11e4-ab6d-005056801329",
}


def migrate_area_refs(apps, schema_editor):
    Area = apps.get_model("catalogs", "NovaPoshtaArea")
    areas = Area.objects.using(schema_editor.connection.alias)
    for old_ref, new_ref in AREA_REFS.items():
        if areas.filter(ref=new_ref).exists():
            areas.filter(ref=old_ref).delete()
        else:
            areas.filter(ref=old_ref).update(ref=new_ref)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0032_novaposhtaarea'),
    ]

    operations = [
        migrations.RunPython(migrate_area_refs, migrations.RunPython.noop),
        migrations.CreateModel(
            name='NovaPoshtaRegion',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False, verbose_name='Ref Новой почты')),
                ('description', models.CharField(max_length=255, verbose_name='Название')),
                ('region_type', models.CharField(max_length=100, verbose_name='Тип района')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='catalogs.novaposhtaarea', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Новая почта: район',
                'verbose_name_plural': 'Новая почта: районы',
                'ordering': ('area__description', 'description'),
            },
        ),
    ]
