# Generated by Django 6.1 on 2026-09-13 19:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0033_novaposhtaregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaSettlement',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False, verbose_name='Ref Новой почты')),
                ('settlement_type', models.UUIDField(verbose_name='Ref типа населённого пункта')),
                ('description', models.CharField(max_length=255, verbose_name='Название')),
                ('description_ru', models.CharField(blank=True, max_length=255, verbose_name='Название на русском')),
                ('description_translit', models.CharField(blank=True, max_length=255, verbose_name='Название латиницей')),
                ('settlement_type_description', models.CharField(max_length=100, verbose_name='Тип населённого пункта')),
                ('settlement_type_description_ru', models.CharField(blank=True, max_length=100, verbose_name='Тип на русском')),
                ('settlement_type_description_translit', models.CharField(blank=True, max_length=100, verbose_name='Тип латиницей')),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Долгота')),
                ('index_1', models.CharField(blank=True, max_length=20, verbose_name='Начальный индекс')),
                ('index_2', models.CharField(blank=True, max_length=20, verbose_name='Конечный индекс')),
                ('index_coatsu_1', models.CharField(blank=True, max_length=20, verbose_name='Код КОАТУУ')),
                ('delivery_1', models.BooleanField(default=False, verbose_name='Доставка: понедельник')),
                ('delivery_2', models.BooleanField(default=False, verbose_name='Доставка: вторник')),
                ('delivery_3', models.BooleanField(default=False, verbose_name='Доставка: среда')),
                ('delivery_4', models.BooleanField(default=False, verbose_name='Доставка: четверг')),
                ('delivery_5', models.BooleanField(default=False, verbose_name='Доставка: пятница')),
                ('delivery_6', models.BooleanField(default=False, verbose_name='Доставка: суббота')),
                ('delivery_7', models.BooleanField(default=False, verbose_name='Доставка: воскресенье')),
                ('special_cash_check', models.BooleanField(default=False, verbose_name='SpecialCashCheck')),
                ('radius_home_delivery', models.PositiveIntegerField(blank=True, null=True, verbose_name='Радиус адресной доставки')),
                ('radius_express_pick_up', models.PositiveIntegerField(blank=True, null=True, verbose_name='Радиус экспресс-забора')),
                ('radius_drop', models.PositiveIntegerField(blank=True, null=True, verbose_name='Радиус сдачи отправлений')),
                ('warehouse', models.BooleanField(default=False, verbose_name='Есть отделения')),
                ('address_delivery_allowed', models.BooleanField(default=False, verbose_name='Адресная доставка доступна')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='catalogs.novaposhtaarea', verbose_name='Область')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='catalogs.novaposhtaregion', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Новая почта: населённый пункт',
                'verbose_name_plural': 'Новая почта: населённые пункты',
                'ordering': ('description', 'ref'),
            },
        ),
    ]
