# Generated by Django 6.1 on 2026-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0034_novaposhtasettlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='address_delivery_allowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Адресная доставка доступна'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='delivery_1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка: понедельник'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='delivery_2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка: вторник'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='delivery_3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка: среда'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='delivery_4',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка: четверг'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='delivery_5',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка: пятница'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='delivery_6',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка: суббота'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='delivery_7',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доставка: воскресенье'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='special_cash_check',
            field=models.BooleanField(blank=True, null=True, verbose_name='SpecialCashCheck'),
        ),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='warehouse',
            field=models.BooleanField(blank=True, null=True, verbose_name='Есть отделения'),
        ),
    ]
