# Generated by Django 6.1 on 2026-09-14 05:43

import django.db.models.deletion
from django.db import migrations, models


def populate_types(apps, schema_editor):
    Settlement = apps.get_model("catalogs", "NovaPoshtaSettlement")
    SettlementType = apps.get_model("catalogs", "NovaPoshtaSettlementType")
    alias = schema_editor.connection.alias
    rows = Settlement.objects.using(alias).order_by().values_list(
        "settlement_type", "settlement_type_description"
    ).distinct()
    for ref, description in rows:
        SettlementType.objects.using(alias).get_or_create(
            ref=ref, defaults={"description": description, "code": ""}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0035_alter_novaposhtasettlement_address_delivery_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaSettlementType',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False, verbose_name='Ref Новой почты')),
                ('description', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Новая почта: тип населённого пункта',
                'verbose_name_plural': 'Новая почта: типы населённых пунктов',
                'ordering': ('description',),
            },
        ),
        migrations.RunPython(populate_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='novaposhtasettlement',
            name='settlement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='catalogs.novaposhtasettlementtype', verbose_name='Тип населённого пункта'),
        ),
    ]
