# Generated by Django 6.1 on 2026-09-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0038_novaposhtaarea_is_active_novaposhtaregion_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaSettlementDetails',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='catalogs.novaposhtasettlement', verbose_name='Населённый пункт')),
                ('address_delivery_allowed', models.BooleanField(verbose_name='Адресная доставка доступна')),
                ('streets_availability', models.BooleanField(verbose_name='Улицы доступны')),
                ('delivery_city_ref', models.UUIDField(verbose_name='Ref города доставки')),
                ('description', models.CharField(max_length=255, verbose_name='Город доставки')),
                ('settlement_type', models.UUIDField(verbose_name='Ref типа города доставки')),
                ('settlement_type_description', models.CharField(max_length=100, verbose_name='Тип города доставки')),
                ('prevent_entry_new_streets_user', models.BooleanField(verbose_name='Запрет ввода новых улиц')),
                ('city_id', models.CharField(max_length=30, verbose_name='CityID')),
                ('special_cash_check', models.BooleanField(verbose_name='SpecialCashCheck')),
                ('area_description', models.CharField(max_length=255, verbose_name='Область города доставки')),
                ('delivery_1', models.BooleanField(verbose_name='Доставка: понедельник')),
                ('delivery_2', models.BooleanField(verbose_name='Доставка: вторник')),
                ('delivery_3', models.BooleanField(verbose_name='Доставка: среда')),
                ('delivery_4', models.BooleanField(verbose_name='Доставка: четверг')),
                ('delivery_5', models.BooleanField(verbose_name='Доставка: пятница')),
                ('delivery_6', models.BooleanField(verbose_name='Доставка: суббота')),
                ('delivery_7', models.BooleanField(verbose_name='Доставка: воскресенье')),
            ],
            options={
                'verbose_name': 'Допданные Новой почты',
                'verbose_name_plural': 'Допданные Новой почты',
            },
        ),
    ]
