# Generated by Django 6.1 on 2026-09-15 12:05

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0039_novaposhtasettlementdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ('last_name', 'first_name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль контактного лица',
                'verbose_name_plural': 'Роли контактных лиц',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('has_viber', models.BooleanField(blank=True, default=None, null=True, verbose_name='Viber')),
                ('has_telegram', models.BooleanField(blank=True, default=None, null=True, verbose_name='Telegram')),
                ('has_whatsapp', models.BooleanField(blank=True, default=None, null=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Телефонный номер',
                'verbose_name_plural': 'Телефонные номера',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='ContractorContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_links', to='catalogs.contactperson', verbose_name='Контактное лицо')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='catalogs.contractor', verbose_name='Контрагент')),
                ('roles', models.ManyToManyField(blank=True, to='catalogs.contactrole', verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Контакт контрагента',
                'verbose_name_plural': 'Контакты контрагента',
            },
        ),
        migrations.AddField(
            model_name='contractor',
            name='contact_persons',
            field=models.ManyToManyField(through='catalogs.ContractorContactPerson', to='catalogs.contactperson', verbose_name='Контактные лица'),
        ),
        migrations.CreateModel(
            name='ContractorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('for_communication', models.BooleanField(default=True, verbose_name='Для связи')),
                ('for_delivery', models.BooleanField(default=False, verbose_name='Для доставки')),
                ('is_primary_for_communication', models.BooleanField(default=False, verbose_name='Основной для связи')),
                ('is_primary_for_delivery', models.BooleanField(default=False, verbose_name='Основной для доставки')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Подпись')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_links', to='catalogs.contractor', verbose_name='Контрагент')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.phonenumber', verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телефон контрагента',
                'verbose_name_plural': 'Телефоны контрагента',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPersonPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('for_communication', models.BooleanField(default=True, verbose_name='Для связи')),
                ('for_delivery', models.BooleanField(default=False, verbose_name='Для доставки')),
                ('is_primary_for_communication', models.BooleanField(default=False, verbose_name='Основной для связи')),
                ('is_primary_for_delivery', models.BooleanField(default=False, verbose_name='Основной для доставки')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Подпись')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_links', to='catalogs.contactperson', verbose_name='Контактное лицо')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.phonenumber', verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телефон контактного лица',
                'verbose_name_plural': 'Телефоны контактного лица',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contactperson',
            name='phones',
            field=models.ManyToManyField(through='catalogs.ContactPersonPhone', to='catalogs.phonenumber', verbose_name='Телефоны'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='phones',
            field=models.ManyToManyField(through='catalogs.ContractorPhone', to='catalogs.phonenumber', verbose_name='Телефоны'),
        ),
        migrations.AddConstraint(
            model_name='contractorcontactperson',
            constraint=models.UniqueConstraint(fields=('contractor', 'contact_person'), name='unique_contractor_contact'),
        ),
        migrations.AddConstraint(
            model_name='contractorphone',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary_for_communication', False), ('for_communication', True), _connector='OR'), name='contractorphone_primary_comm_purpose'),
        ),
        migrations.AddConstraint(
            model_name='contractorphone',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary_for_delivery', False), ('for_delivery', True), _connector='OR'), name='contractorphone_primary_delivery_purpose'),
        ),
        migrations.AddConstraint(
            model_name='contractorphone',
            constraint=models.UniqueConstraint(fields=('contractor', 'phone'), name='unique_contractor_phone'),
        ),
        migrations.AddConstraint(
            model_name='contractorphone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_for_communication', True)), fields=('contractor',), name='unique_contractor_primary_comm'),
        ),
        migrations.AddConstraint(
            model_name='contractorphone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_for_delivery', True)), fields=('contractor',), name='unique_contractor_primary_delivery'),
        ),
        migrations.AddConstraint(
            model_name='contactpersonphone',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary_for_communication', False), ('for_communication', True), _connector='OR'), name='contactpersonphone_primary_comm_purpose'),
        ),
        migrations.AddConstraint(
            model_name='contactpersonphone',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary_for_delivery', False), ('for_delivery', True), _connector='OR'), name='contactpersonphone_primary_delivery_purpose'),
        ),
        migrations.AddConstraint(
            model_name='contactpersonphone',
            constraint=models.UniqueConstraint(fields=('contact_person', 'phone'), name='unique_contact_person_phone'),
        ),
        migrations.AddConstraint(
            model_name='contactpersonphone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_for_communication', True)), fields=('contact_person',), name='unique_contact_person_primary_comm'),
        ),
        migrations.AddConstraint(
            model_name='contactpersonphone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_for_delivery', True)), fields=('contact_person',), name='unique_contact_person_primary_delivery'),
        ),
    ]
