# Generated by Django 6.1 on 2026-09-15 18:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0042_contact_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaWarehouse',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('ref', models.UUIDField(primary_key=True, serialize=False, verbose_name='Ref Новой почты')),
                ('settlement_ref', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='SettlementRef источника')),
                ('city_ref', models.UUIDField(blank=True, null=True, verbose_name='Ref города доставки')),
                ('warehouse_type_ref', models.UUIDField(verbose_name='Ref типа отделения')),
                ('number', models.CharField(max_length=30, verbose_name='Номер')),
                ('description', models.CharField(max_length=1000, verbose_name='Название')),
                ('description_ru', models.CharField(blank=True, max_length=1000, verbose_name='Название на русском')),
                ('short_address', models.CharField(blank=True, max_length=1000, verbose_name='Краткий адрес')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Категория')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Статус Новой почты')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('settlement_description', models.CharField(blank=True, max_length=255, verbose_name='Населённый пункт источника')),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Долгота')),
                ('total_max_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Максимальный вес отправления, кг')),
                ('place_max_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Максимальный вес места, кг')),
                ('schedule', models.JSONField(blank=True, default=dict, verbose_name='График работы')),
                ('reception', models.JSONField(blank=True, default=dict, verbose_name='График приёма')),
                ('delivery', models.JSONField(blank=True, default=dict, verbose_name='График выдачи / доставки')),
                ('sending_dimensions', models.JSONField(blank=True, default=dict, verbose_name='Ограничения габаритов отправки')),
                ('receiving_dimensions', models.JSONField(blank=True, default=dict, verbose_name='Ограничения габаритов получения')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Все данные Новой почты')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='catalogs.novaposhtasettlement', verbose_name='Населённый пункт')),
            ],
            options={
                'verbose_name': 'Новая почта: отделение / почтомат',
                'verbose_name_plural': 'Новая почта: отделения и почтоматы',
                'ordering': ('description', 'ref'),
            },
        ),
    ]
