# Generated by Django 6.1 on 2026-09-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0043_novaposhtawarehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='beacon_code',
            field=models.CharField(blank=True, max_length=1000, verbose_name='BeaconCode'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='bicycle_parking',
            field=models.BooleanField(blank=True, null=True, verbose_name='Велопарковка'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='can_get_money_transfer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Получение денежных переводов'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='city_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='city_description_ru',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Город доставки на русском'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='deny_to_select',
            field=models.BooleanField(blank=True, null=True, verbose_name='Запрещён выбор отделения'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='direct',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Направление (Direct)'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='district_code',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Код подразделения (DistrictCode)'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='generator_enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Генератор'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='has_fitting_room',
            field=models.BooleanField(blank=True, null=True, verbose_name='Примерочная'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='has_mirror',
            field=models.BooleanField(blank=True, null=True, verbose_name='Зеркало'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='international_shipping',
            field=models.BooleanField(blank=True, null=True, verbose_name='Международные отправления'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='location',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Расположение (Location)'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='max_declared_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Максимальная объявленная стоимость'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='only_receiving_parcel',
            field=models.BooleanField(blank=True, null=True, verbose_name='Только получение посылок'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='payment_access',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доступность оплаты (PaymentAccess)'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='pos_terminal',
            field=models.BooleanField(blank=True, null=True, verbose_name='POS-терминал'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='post_finance',
            field=models.BooleanField(blank=True, null=True, verbose_name='Финансовые услуги (PostFinance)'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='post_machine_type',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Режим почтомата'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='postomat_for',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Назначение почтомата'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='region_city',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Региональный центр'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='self_service_workplaces_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рабочие места самообслуживания'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='settlement_area_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Область источника'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='settlement_regions_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Район источника'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='settlement_type_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Тип населённого пункта'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='settlement_type_description_ru',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Тип населённого пункта на русском'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='short_address_ru',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Краткий адрес на русском'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='site_key',
            field=models.CharField(blank=True, db_index=True, max_length=1000, verbose_name='SiteKey Новой почты'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='status_date',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Дата статуса в источнике'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='warehouse_for_agent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Отделение для агента'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='warehouse_illusha',
            field=models.BooleanField(blank=True, null=True, verbose_name='WarehouseIllusha'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='warehouse_index',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Индекс отделения'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='work_in_mobile_awis',
            field=models.BooleanField(blank=True, null=True, verbose_name='Работа в мобильном AWIS'),
        ),
    ]
