# Generated by Django 6.1 on 2026-09-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0045_backfill_warehouse_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaWarehouseType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('ref', models.UUIDField(primary_key=True, serialize=False, verbose_name='Ref Новой почты')),
                ('description', models.CharField(max_length=255, verbose_name='Название')),
                ('description_ru', models.CharField(blank=True, max_length=255, verbose_name='Название на русском')),
            ],
            options={
                'verbose_name': 'Новая почта: тип отделения',
                'verbose_name_plural': 'Новая почта: типы отделений',
                'ordering': ('description', 'ref'),
            },
        ),
        migrations.AddField(
            model_name='novaposhtawarehouse',
            name='warehouse_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='catalogs.novaposhtawarehousetype', verbose_name='Тип отделения'),
        ),
    ]
