# Generated by Django 6.0.4 on 2026-04-30 12:32

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0005_contractorlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Номер')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, help_text='Документ проведен и учитывается в остатках', verbose_name='Применен')),
                ('dt_applied', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата применения')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='В корзине')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='catalogs.contractor', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Установка цен поставщика',
                'verbose_name_plural': 'Установки цен поставщика',
                'ordering': ['-dt_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(currency_choices=[('UAH', 'UAH'), ('USD', 'USD')], decimal_places=2, default_currency='UAH', max_digits=12, verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.product', verbose_name='Товар')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.supplierpricelist', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Позиции прайса',
            },
        ),
    ]
