# Generated by Django 6.0.4 on 2026-04-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpricelist',
            name='number',
        ),
    ]
