# Generated by Django 6.0.4 on 2026-04-30 13:28

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_contractorlink'),
        ('documents', '0002_remove_supplierpricelist_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpricelist',
            name='dt_applied',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='supplierpricelist',
            name='is_applied',
            field=models.BooleanField(db_index=True, default=False, help_text='Документ проведен', verbose_name='Проведен'),
        ),
        migrations.AlterField(
            model_name='supplierpricelist',
            name='to_remove',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, help_text='Документ проведен', verbose_name='Проведен')),
                ('dt_applied', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата проведения')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='catalogs.contractor', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заказ поставщику',
                'verbose_name_plural': 'Заказы поставщикам',
                'ordering': ['-dt_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Количество')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(currency_choices=[('UAH', 'UAH'), ('USD', 'USD')], decimal_places=2, default_currency='UAH', max_digits=12, verbose_name='Цена за ед.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.purchaseorder', verbose_name='Документ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
