# Generated by Django 6.0.4 on 2026-04-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_contractorlink'),
        ('documents', '0003_alter_supplierpricelist_dt_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, help_text='Документ проведен', verbose_name='Проведен')),
                ('dt_applied', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата проведения')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Покупатель (ФИО/Ник)')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('done', 'Выполнен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ покупателя',
                'verbose_name_plural': 'Заказы покупателей',
                'ordering': ['-dt_created'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
