# Generated by Django 6.0.4 on 2026-04-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_contractorlink'),
        ('documents', '0004_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='catalogs.contractor', verbose_name='Покупатель'),
            preserve_default=False,
        ),
    ]
