# Generated by Django 6.0.4 on 2026-04-30 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_contractorlink'),
        ('documents', '0005_remove_salesorder_customer_name_salesorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='catalogs.contractor', verbose_name='Покупатель'),
        ),
    ]
