# Generated by Django 6.0.4 on 2026-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_salesorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед. (UAH)'),
        ),
    ]
