# Generated by Django 6.0.4 on 2026-05-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_remove_contractorlegaldetails_iban'),
        ('documents', '0007_remove_purchaseorderitem_price_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesOrder',
            new_name='CustomerOrder',
        ),
        migrations.RenameModel(
            old_name='SalesOrderItem',
            new_name='CustomerOrderItem',
        ),
    ]
