# Generated by Django 6.0.4 on 2026-05-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_remove_contractorlegaldetails_iban'),
        ('documents', '0008_rename_salesorder_customerorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='document',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='catalogs.contractor', verbose_name='Покупатель'),
        ),
        migrations.DeleteModel(
            name='CustomerOrderItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
