# Generated by Django 6.0.4 on 2026-05-02 06:36

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_remove_contractorlegaldetails_iban'),
        ('documents', '0009_remove_purchaseorderitem_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total_price', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('price')), output_field=models.DecimalField(decimal_places=2, max_digits=10), verbose_name='Сумма')),
                ('sort_order_purchase', models.PositiveIntegerField(default=0, verbose_name='Порядок в закупке')),
                ('sort_order_customer', models.PositiveIntegerField(default=0, verbose_name='Порядок в продаже')),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.customerorder', verbose_name='Заказ покупателя')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalogs.product', verbose_name='Товар')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.purchaseorder', verbose_name='Заказ поставщику')),
                ('warehouse', models.ForeignKey(help_text='Склад отгрузки или приемки для этой строки', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalogs.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
                'ordering': ['sort_order_purchase', 'sort_order_customer'],
            },
        ),
    ]
