# Generated by Django 6.0.4 on 2026-05-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sort_order_customer',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок в продаже'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sort_order_purchase',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок в закупке'),
        ),
    ]
