# Generated by Django 6.0.4 on 2026-05-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_orderitem_sort_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ покупателя', 'verbose_name_plural': 'Заказы покупателей'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ поставщику', 'verbose_name_plural': 'Заказы поставщикам'},
        ),
        migrations.AlterModelOptions(
            name='supplierpricelist',
            options={'ordering': ['-created'], 'verbose_name': 'Установка цен поставщика', 'verbose_name_plural': 'Установки цен поставщика'},
        ),
        migrations.RenameField(
            model_name='customerorder',
            old_name='dt_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='customerorder',
            old_name='dt_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='dt_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='dt_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='supplierpricelist',
            old_name='dt_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='supplierpricelist',
            old_name='dt_updated',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='is_applied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Проведен'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customer_order',
            field=models.ForeignKey(blank=True, limit_choices_to={'to_remove': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.customerorder', verbose_name='Заказ покупателя'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='purchase_order',
            field=models.ForeignKey(blank=True, limit_choices_to={'to_remove': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.purchaseorder', verbose_name='Заказ поставщику'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='is_applied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Проведен'),
        ),
        migrations.AlterField(
            model_name='supplierpricelist',
            name='is_applied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Проведен'),
        ),
    ]
