# Generated by Django 6.0.4 on 2026-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_customerorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='dt_applied',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='dt_applied',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='supplierpricelist',
            name='dt_applied',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
    ]
