# Generated by Django 6.0.4 on 2026-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_customerorder_dt_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
