# Generated by Django 6.0.4 on 2026-05-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_customerorder_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='test_date',
        ),
    ]
