# Generated by Django 6.0.4 on 2026-05-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_contractor_primary_account'),
        ('documents', '0016_orderitem_created_orderitem_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Проведен')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('dt_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='catalogs.contractor', verbose_name='Поставщик')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
