# Generated by Django 6.0.4 on 2026-05-04 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_contractor_primary_account'),
        ('documents', '0017_purchaseinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogs.bankaccount', verbose_name='Счет для оплаты'),
        ),
    ]
