# Generated by Django 6.0.5 on 2026-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_purchaseinvoice_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sort_order_customer',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок в продаже'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sort_order_purchase',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок в закупке'),
        ),
    ]
