# Generated by Django 6.0.5 on 2026-05-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0023_alter_organization_created_and_more'),
        ('documents', '0019_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpricelist',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если цена общая для всех организаций', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organization', verbose_name='Организация'),
        ),
    ]
