# Generated by Django 6.0.5 on 2026-05-12 07:24

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0023_alter_organization_created_and_more'),
        ('documents', '0020_supplierpricelist_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='organization',
            field=models.ForeignKey(default=documents.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='organization',
            field=models.ForeignKey(default=documents.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(default=documents.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Организация'),
        ),
    ]
