# Generated by Django 6.0.5 on 2026-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_customerorder_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'Входящий счет', 'verbose_name_plural': 'Входящие счета'},
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='orders',
            field=models.ManyToManyField(related_name='invoices', to='documents.purchaseorder', verbose_name='Основание: Заказы поставщику'),
        ),
    ]
