# Generated by Django 6.0.5 on 2026-05-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_purchaseinvoice_options_purchaseinvoice_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.purchaseinvoice')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='documents.orderitem', verbose_name='Строка заказа')),
            ],
            options={
                'verbose_name': 'Позиция входящего счета',
                'verbose_name_plural': 'Позиции входящего счета',
                'ordering': ['sort_order'],
            },
        ),
    ]
