# Generated by Django 6.0.5 on 2026-05-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_method_customer',
            field=models.CharField(choices=[('prepaid', 'Оплата по счету'), ('postpaid', 'Постоплата')], default='prepaid', max_length=20, verbose_name='Оплата покупателем'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_method_purchase',
            field=models.CharField(choices=[('prepaid', 'Оплата по счету'), ('postpaid', 'Постоплата')], default='prepaid', max_length=20, verbose_name='Оплата поставщику'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок'),
        ),
    ]
