# Generated by Django 6.0.5 on 2026-05-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_orderitem_payment_method_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='orders',
            field=models.ManyToManyField(blank=True, help_text='Используется только для фильтрации доступных позиций в строках счета. Фактическая связь устанавливается на уровне конкретных товаров.', related_name='invoices', to='documents.purchaseorder', verbose_name='Основание: Заказы поставщику'),
        ),
    ]
