# Generated by Django 6.0.5 on 2026-05-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0023_alter_organization_created_and_more'),
        ('documents', '0025_alter_purchaseinvoice_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если в будут использватьбся разные организации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organization', verbose_name='Организация'),
        ),
    ]
