# Generated by Django 6.0.5 on 2026-05-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0023_alter_organization_created_and_more'),
        ('documents', '0026_alter_purchaseorder_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Если не указано, берется из шапки заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organization', verbose_name='Организация'),
        ),
    ]
