# Generated by Django 6.0.5 on 2026-05-15 12:50

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0023_alter_organization_created_and_more'),
        ('documents', '0027_orderitem_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если в будут использоваться разные организации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='PaymentOrderOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Проведен')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('dt_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
                ('bank_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Комиссия банка')),
                ('total_debited', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('amount'), '+', models.F('bank_commission')), output_field=models.DecimalField(decimal_places=2, max_digits=12), verbose_name='Всего списано')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.bankaccount', verbose_name='Счет контрагента')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.contractor', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Наша организация')),
            ],
            options={
                'verbose_name': 'Платеж исходящий',
                'verbose_name_plural': 'Платежи исходящие',
            },
        ),
        migrations.CreateModel(
            name='PaymentOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма оплаты')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.purchaseinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.paymentorderout')),
            ],
            options={
                'verbose_name': 'Оплата счета',
                'verbose_name_plural': 'Оплата счетов',
            },
        ),
        migrations.AddField(
            model_name='paymentorderout',
            name='purchase_invoices',
            field=models.ManyToManyField(through='documents.PaymentOutItem', to='documents.purchaseinvoice', verbose_name='Оплаченные счета поставщиков'),
        ),
    ]
