# Generated by Django 6.0.5 on 2026-05-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_alter_purchaseorder_organization_paymentorderout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentorderout',
            old_name='bank_account',
            new_name='contractor_bank_account',
        ),
    ]
