# Generated by Django 6.1 on 2026-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_rename_bank_account_paymentorderout_contractor_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpriceitem',
            name='price_type',
            field=models.CharField(choices=[('small_wholesale', 'Мелкий опт'), ('wholesale', 'Опт'), ('large_wholesale', 'Крупный опт')], default='wholesale', max_length=20, verbose_name='Тип цены'),
        ),
    ]
