# Generated by Django 6.1 on 2026-08-21 07:47

import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_supplierpriceitem_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpriceitem',
            name='price_type',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='price_type',
            field=models.CharField(blank=True, choices=[('small_wholesale', 'Мелкий опт'), ('wholesale', 'Опт'), ('large_wholesale', 'Крупный опт')], help_text='Если не выбран, используется тип цены по умолчанию у поставщика', max_length=20, null=True, verbose_name='Тип цены'),
        ),
        migrations.AddField(
            model_name='supplierpriceitem',
            name='large_wholesale_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'UAH'), max_digits=12, verbose_name='Крупный опт'),
        ),
        migrations.AddField(
            model_name='supplierpriceitem',
            name='large_wholesale_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='supplierpriceitem',
            name='small_wholesale_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'UAH'), max_digits=12, verbose_name='Мелкий опт'),
        ),
        migrations.AddField(
            model_name='supplierpriceitem',
            name='small_wholesale_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='supplierpriceitem',
            name='wholesale_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'UAH'), max_digits=12, verbose_name='Опт'),
        ),
        migrations.AddField(
            model_name='supplierpriceitem',
            name='wholesale_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3),
        ),
    ]
