# Generated by Django 6.1 on 2026-08-21 07:48

from django.db import migrations


def copy_existing_prices_to_wholesale(apps, schema_editor):
    SupplierPriceItem = apps.get_model("documents", "SupplierPriceItem")

    for item in SupplierPriceItem.objects.all().iterator():
        item.wholesale_price = item.price
        item.save(update_fields=["wholesale_price", "wholesale_price_currency"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0031_remove_supplierpriceitem_price_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_existing_prices_to_wholesale,
            migrations.RunPython.noop,
        ),
    ]
