# Generated by Django 6.1 on 2026-08-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_populate_wholesale_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='РРЦ'),
        ),
    ]
