# Generated by Django 6.1 on 2026-08-31 04:54

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0028_retailstore'),
        ('documents', '0033_orderitem_rrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Проведен')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('dt_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(blank=True, help_text='Оставьте пустым, если цена общая для всех организаций', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organization', verbose_name='Организация')),
                ('retail_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='catalogs.retailstore', verbose_name='Розничный магазин')),
            ],
            options={
                'verbose_name': 'Установка розничных цен',
                'verbose_name_plural': 'Установки розничных цен',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='Розничная цена')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.product', verbose_name='Товар')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.retailpricelist', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Позиция розничного прайса',
                'verbose_name_plural': 'Позиции розничного прайса',
            },
        ),
    ]
