# Generated by Django 6.1 on 2026-08-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0028_retailstore'),
        ('documents', '0034_retailpricelist_retailpriceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailpricelist',
            name='retail_store',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если прайс действует для всех магазинов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='catalogs.retailstore', verbose_name='Розничный магазин'),
        ),
    ]
