# Generated by Django 6.1 on 2026-08-31 05:08

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0029_retailstore_is_default'),
        ('documents', '0035_alter_retailpricelist_retail_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailpricelist',
            name='retail_store',
            field=models.ForeignKey(blank=True, default=documents.models.get_default_retail_store_id, help_text='Оставьте пустым, если прайс действует для всех магазинов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='catalogs.retailstore', verbose_name='Розничный магазин'),
        ),
    ]
