# Generated by Django 6.1 on 2026-08-31 05:12

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0029_retailstore_is_default'),
        ('documents', '0036_alter_retailpricelist_retail_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='retail_store',
            field=models.ForeignKey(default=documents.models.get_default_retail_store_id, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='catalogs.retailstore', verbose_name='Розничный магазин'),
        ),
    ]
