# Generated by Django 6.1 on 2026-08-31 05:47

import django.db.models.expressions
from django.db import migrations, models


def copy_legacy_prices(apps, schema_editor):
    OrderItem = apps.get_model("documents", "OrderItem")
    items_to_update = []

    for item in OrderItem.objects.all().iterator():
        if item.purchase_order_id:
            item.purchase_price = item.price
        if item.customer_order_id:
            item.customer_price = item.price
        items_to_update.append(item)

    OrderItem.objects.bulk_update(
        items_to_update,
        ["purchase_price", "customer_price"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_customerorder_retail_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупочная цена'),
        ),
        migrations.RunPython(copy_legacy_prices, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_total_price',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('customer_price')), output_field=models.DecimalField(decimal_places=2, max_digits=10, null=True), verbose_name='Сумма продажи'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_total_price',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('purchase_price')), output_field=models.DecimalField(decimal_places=2, max_digits=10, null=True), verbose_name='Сумма закупки'),
        ),
    ]
