# Generated by Django 6.1 on 2026-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_remove_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_method_purchase',
            field=models.CharField(choices=[('prepaid', 'Предоплата'), ('postpaid', 'Отсрочка платежа')], default='prepaid', max_length=20, verbose_name='Оплата поставщику'),
        ),
    ]
