# Generated by Django 6.1 on 2026-08-31 11:40

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0029_retailstore_is_default'),
        ('documents', '0039_alter_orderitem_payment_method_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Проведен')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('dt_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='catalogs.ourbankaccount', verbose_name='Счет для оплаты')),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='catalogs.contractor', verbose_name='Покупатель')),
                ('orders', models.ManyToManyField(blank=True, help_text='Используется для выбора доступных позиций. Фактическая связь устанавливается на уровне строк счета.', related_name='sales_invoices', to='documents.customerorder', verbose_name='Основание: Заказы покупателей')),
                ('organization', models.ForeignKey(default=documents.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Счет на оплату',
                'verbose_name_plural': 'Счета на оплату',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.salesinvoice', verbose_name='Счет на оплату')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_item', to='documents.orderitem', verbose_name='Строка заказа')),
            ],
            options={
                'verbose_name': 'Позиция счета на оплату',
                'verbose_name_plural': 'Позиции счета на оплату',
                'ordering': ['sort_order'],
            },
        ),
    ]
