# Generated by Django 6.1 on 2026-08-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_salesinvoice_salesinvoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_method_purchase',
        ),
    ]
