# Generated by Django 6.1 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0030_measurementunit_product_unit"),
        ("documents", "0041_remove_orderitem_payment_method_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                max_digits=14,
                verbose_name="Количество",
            ),
        ),
    ]
