# Generated by Django 6.1 on 2026-09-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'verbose_name': 'Счет на оплату покупателю', 'verbose_name_plural': 'Счета на оплату покупателям'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Позиция счета на оплату покупателю', 'verbose_name_plural': 'Позиции счета на оплату покупателю'},
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.salesinvoice', verbose_name='Счет на оплату покупателю'),
        ),
    ]
