# Generated by Django 6.1 on 2026-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0043_alter_salesinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoutitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
