# Generated by Django 6.1 on 2026-09-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0030_measurementunit_product_unit'),
        ('documents', '0044_alter_paymentoutitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorderout',
            name='our_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payments', to='catalogs.ourbankaccount', verbose_name='С нашего счета'),
        ),
    ]
