# Generated by Django 6.1 on 2026-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0045_paymentorderout_our_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorderout',
            name='category',
            field=models.CharField(choices=[('goods', 'За товары'), ('services', 'За услуги'), ('customer_refund', 'Возврат покупателю')], default='goods', max_length=20, verbose_name='Категория платежа'),
        ),
    ]
