# Generated by Django 6.1 on 2026-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0047_paymentorderout_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorderout',
            name='uetr',
            field=models.UUIDField(blank=True, null=True, verbose_name='UETR СЕП'),
        ),
        migrations.AddField(
            model_name='paymentorderout',
            name='verification_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код проверки'),
        ),
    ]
