# Generated by Django 6.1 on 2026-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0048_paymentorderout_uetr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentoutitem',
            options={'ordering': ('sort_order', 'pk'), 'verbose_name': 'Оплата счета', 'verbose_name_plural': 'Оплата счетов'},
        ),
        migrations.AddField(
            model_name='paymentoutitem',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок'),
        ),
    ]
