# Generated by Django 6.1 on 2026-09-12 16:02

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import documents.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0030_measurementunit_product_unit'),
        ('documents', '0049_alter_paymentoutitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Проведен')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('dt_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(default=documents.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Организация')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='documents.purchaseorder', verbose_name='Заказ поставщику')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.warehouse', verbose_name='Склад приёмки')),
            ],
            options={
                'verbose_name': 'Поступление товаров',
                'verbose_name_plural': 'Поступления товаров',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Получено')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Закупочная цена')),
                ('total_price', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('purchase_price')), output_field=models.DecimalField(decimal_places=2, max_digits=20), verbose_name='Сумма')),
                ('sort_order', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='documents.orderitem', verbose_name='Строка заказа поставщику')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.goodsreceipt')),
            ],
            options={
                'verbose_name': 'Позиция поступления',
                'verbose_name_plural': 'Позиции поступления',
                'ordering': ('sort_order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('receipt', 'order_item'), name='unique_receipt_order_item'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='receipt_quantity_positive'), models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='receipt_price_nonnegative')],
            },
        ),
    ]
