# Generated by Django 6.1 on 2026-09-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0050_goodsreceipt_goodsreceiptitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goodsreceiptitem',
            name='receipt_price_nonnegative',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='purchase_price',
        ),
    ]
