# Generated by Django 6.1 on 2026-09-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0052_invoiceitem_partial_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier_delivery_note_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расходной накладной поставщика'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier_delivery_note_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер расходной накладной поставщика'),
        ),
    ]
