# Generated by Django 6.1 on 2026-09-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0053_goodsreceipt_supplier_delivery_note_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счёта поставщика'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер счёта поставщика'),
        ),
    ]
