# Generated by Django 6.1 on 2026-09-13 15:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0030_measurementunit_product_unit'),
        ('documents', '0055_goodsreceipt_multiple_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrderIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Проведен')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('dt_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
                ('payment_number', models.CharField(max_length=100, verbose_name='Номер платёжного документа')),
                ('verification_code', models.CharField(blank=True, max_length=255, verbose_name='Код проверки')),
                ('uetr', models.UUIDField(blank=True, null=True, verbose_name='UETR СЕП')),
                ('category', models.CharField(choices=[('goods_services', 'За товары и услуги'), ('supplier_refund', 'Возврат товара поставщику'), ('other', 'Прочие')], default='goods_services', max_length=20, verbose_name='Категория платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.contractor', verbose_name='Контрагент')),
                ('contractor_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.contractorbankaccount', verbose_name='Счет контрагента')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Наша организация')),
                ('our_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='catalogs.ourbankaccount', verbose_name='На наш счет')),
            ],
            options={
                'verbose_name': 'Платеж входящий',
                'verbose_name_plural': 'Платежи входящие',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='incoming_payment_amount_positive')],
            },
        ),
    ]
