# Generated by Django 6.1 on 2026-09-13 16:00

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import documents.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0030_measurementunit_product_unit'),
        ('documents', '0056_paymentorderin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Проведен')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('dt_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('delivery_note_number', models.CharField(blank=True, max_length=100, verbose_name='Номер расходной накладной')),
                ('delivery_note_date', models.DateField(blank=True, null=True, verbose_name='Дата расходной накладной')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='catalogs.contractor', verbose_name='Покупатель')),
                ('organization', models.ForeignKey(default=documents.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Реализация товаров и услуг',
                'verbose_name_plural': 'Реализации товаров и услуг',
            },
        ),
        migrations.CreateModel(
            name='SalesDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена продажи')),
                ('total_price', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('price')), output_field=models.DecimalField(decimal_places=2, max_digits=20), verbose_name='Сумма')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.salesdocument')),
                ('order_item', models.ForeignKey(blank=True, limit_choices_to={'customer_order__isnull': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_items', to='documents.orderitem', verbose_name='Строка заказа покупателя')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.product', verbose_name='Товар / услуга')),
            ],
            options={
                'verbose_name': 'Позиция реализации',
                'verbose_name_plural': 'Позиции реализации',
                'ordering': ('sort_order', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_document_quantity_positive'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='sales_document_price_nonnegative')],
            },
        ),
    ]
