# Generated by Django 6.1 on 2026-09-13 16:05

import django.db.models.deletion
from django.db import migrations, models


def link_orders(apps, schema_editor):
    Item = apps.get_model("documents", "SalesDocumentItem")
    Document = apps.get_model("documents", "SalesDocument")
    for item in Item.objects.using(schema_editor.connection.alias).select_related("order_item"):
        if not item.order_item_id or not item.order_item.customer_order_id:
            raise RuntimeError("Сначала свяжите все строки реализации со строками заказов покупателей.")
        if item.product_id != item.order_item.product_id or item.price != item.order_item.customer_price:
            raise RuntimeError("Цена и товар реализации должны совпадать со строкой заказа перед переносом.")
        Document.objects.using(schema_editor.connection.alias).get(pk=item.document_id).orders.add(item.order_item.customer_order_id)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0057_salesdocument_salesdocumentitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesdocumentitem',
            name='sales_document_price_nonnegative',
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='sales_documents', to='documents.customerorder', verbose_name='Основание: Заказы покупателей'),
        ),
        migrations.RunPython(link_orders, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='salesdocumentitem',
            name='order_item',
            field=models.ForeignKey(limit_choices_to={'customer_order__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_items', to='documents.orderitem', verbose_name='Строка заказа покупателя'),
        ),
        migrations.AddConstraint(
            model_name='salesdocumentitem',
            constraint=models.UniqueConstraint(fields=('document', 'order_item'), name='unique_sales_document_order_item'),
        ),
        migrations.RemoveField(
            model_name='salesdocumentitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesdocumentitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='salesdocumentitem',
            name='price',
        ),
    ]
