# Generated by Django 6.1 on 2026-09-13 16:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def copy_order_quantities(apps, schema_editor):
    Item = apps.get_model("documents", "SalesInvoiceItem")
    for item in Item.objects.using(schema_editor.connection.alias).select_related("order_item"):
        item.quantity = item.order_item.quantity
        item.save(update_fields=["quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0058_remove_salesdocumentitem_sales_document_price_nonnegative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма оплаты')),
            ],
            options={
                'verbose_name': 'Оплата счета',
                'verbose_name_plural': 'Оплата счетов',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Позиция счета покупателю', 'verbose_name_plural': 'Позиции счета покупателю'},
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Количество по счёту'),
        ),
        migrations.RunPython(copy_order_quantities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="salesinvoiceitem", name="quantity",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000001"))],
                verbose_name="Количество по счёту"),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_items', to='documents.orderitem', verbose_name='Строка заказа'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'order_item'), name='unique_sales_invoice_order_item'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_invoice_quantity_positive'),
        ),
        migrations.AddField(
            model_name='paymentinitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.salesinvoice'),
        ),
        migrations.AddField(
            model_name='paymentinitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.paymentorderin'),
        ),
        migrations.AddField(
            model_name='paymentorderin',
            name='sales_invoices',
            field=models.ManyToManyField(blank=True, through='documents.PaymentInItem', to='documents.salesinvoice', verbose_name='Оплаченные счета покупателей'),
        ),
    ]
