# Generated by Django 6.1 on 2026-09-13 17:05

import django.core.validators
import django.db.models.deletion
import documents.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0031_deliverymethod'),
        ('documents', '0059_paymentinitem_alter_salesinvoiceitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Проведен')),
                ('to_remove', models.BooleanField(db_index=True, default=False, verbose_name='Помечен на удаление')),
                ('dt_applied', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('status', models.CharField(choices=[('preparing', 'Готовится'), ('handed', 'Передано'), ('delivered', 'Доставлено'), ('returned', 'Возвращено')], default='preparing', max_length=20, verbose_name='Статус доставки')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Получатель')),
                ('recipient_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон получателя')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('destination', models.CharField(choices=[('branch', 'Отделение / почтомат'), ('address', 'Адрес')], default='branch', max_length=20, verbose_name='Куда доставить')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Город доставки')),
                ('branch', models.CharField(blank=True, max_length=255, verbose_name='Отделение / почтомат')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Номер ТТН')),
                ('pickup_location', models.CharField(blank=True, max_length=255, verbose_name='Место самовывоза')),
                ('received_by', models.CharField(blank=True, max_length=255, verbose_name='Кто получил')),
                ('handover_confirmed', models.BooleanField(default=False, verbose_name='Передача получателю подтверждена')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.deliverymethod', verbose_name='Способ доставки')),
                ('organization', models.ForeignKey(default=documents.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, to='catalogs.organization', verbose_name='Организация')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='documents.salesdocument', verbose_name='Основание: Реализация')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Количество')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='documents.salesdocumentitem', verbose_name='Строка реализации')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.shipment')),
            ],
            options={
                'verbose_name': 'Позиция отгрузки',
                'verbose_name_plural': 'Позиции отгрузки',
                'ordering': ('sort_order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('shipment', 'sales_item'), name='unique_shipment_sales_item'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shipment_quantity_positive')],
            },
        ),
    ]
